# Server settings (ServerProperties)
server:
 port: 8081
 address: 127.0.0.1
 sessionTimeout: 30
 contextPath: /boot

# Tomcat specifics
tomcat:
  accessLogEnabled: false
  protocolHeader: x-forwarded-proto
  remoteIpHeader: x-forwarded-for
  basedir:
  backgroundProcessorDelay: 30 # secs

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/huajiemu
  username: root
  password: 123456
